SDA EQU P2.0 ; EEPRM SDA pin
SCL 	 EQU  P2.1 ; EEPRM SCL pin  
EN       EQU  P2.7 ; LCD E     Pin
RS       EQU  P2.6 ; LCD RS    Pin
RW       EQU  P2.5 ; LCD R/W   Pin
LCD_DATA EQU  P0   ; LCD D7-D0 Pins

ORG 0000H
CLR RW ; LCD Write Mode Selected
LCALL CLEAR_LCD ; Clear the LCD
LCALL INTRO
LCALL CHOICE_R_OR_W
INVALID_OPTION:
	LCALL BUTTON_4X4
CHECK_OPTION_R:
	CJNE A,#01H,CHECK_OPTION_W
	LJMP READ_MODE
CHECK_OPTION_W: 
	CJNE A,#02H,INVALID_OPTION
	LJMP WRITE_MODE

WRITE_MODE:
	LCALL WRITE_INFORMATION
	LCALL BUTTON_4X4
	SWAP A
	MOV 20H,A
	SWAP A
	LCALL NUMBER_TO_ASCII
	MOV LCD_DATA,A
	LCALL SEND_LCD_DATA
	LCALL BUTTON_4X4
	XCH A,20H
	ORL A,20H
	XCH A,20H
	LCALL NUMBER_TO_ASCII
	MOV LCD_DATA,A
	LCALL SEND_LCD_DATA
	LCALL LCD_SECOND_LINE_C
	LCALL BUTTON_4X4
	SWAP A
	MOV 21H,A
	SWAP A
	LCALL NUMBER_TO_ASCII
	MOV LCD_DATA,A
	LCALL SEND_LCD_DATA
	LCALL BUTTON_4X4
	XCH A,21H
	ORL A,21H
	XCH A,21H
	LCALL NUMBER_TO_ASCII
	MOV LCD_DATA,A
	LCALL SEND_LCD_DATA
	LCALL EEPROM_WRITE
	LCALL DELAY_500ms
	LCALL DONE
	LCALL DELAY_1s
	LJMP RESET
	
READ_MODE:
	LCALL READ_INFORMATION
	LCALL BUTTON_4X4
	SWAP A
	MOV 30H,A
	SWAP A
	LCALL NUMBER_TO_ASCII
	MOV LCD_DATA,A
	LCALL SEND_LCD_DATA
	LCALL BUTTON_4X4
	XCH A,30H
	ORL A,30H
	XCH A,30H
	LCALL NUMBER_TO_ASCII
	MOV LCD_DATA,A
	LCALL SEND_LCD_DATA
	LCALL LCD_SECOND_LINE_C
	LCALL EEPROM_READ
	MOV A,31H
	SWAP A
	ANL A,#0FH
	LCALL NUMBER_TO_ASCII
	MOV LCD_DATA,A
	LCALL SEND_LCD_DATA
	MOV A,31H
	ANL A,#0FH
	LCALL NUMBER_TO_ASCII
	MOV LCD_DATA,A
	LCALL SEND_LCD_DATA
	LCALL DELAY_1s
	LJMP RESET	
	
EEPROM_READ: ; Read the EEPROM address which is in 30H and the read data will be stored in 31H
	LCALL I2C_START
	MOV A,#0A0H ; A command for AT21C02A for writing
	LCALL I2C_WRITE
	MOV A,30H ; Send the Target Address to be read
	LCALL I2C_WRITE
	LCALL I2C_START
	MOV A,#0A1H ; A command for AT21C02A for reading
	LCALL I2C_WRITE
	LCALL I2C_READ
	MOV 31H,A ; Store the recieved data in 31H
	LCALL I2C_STOP
	RET
	
	
EEPROM_WRITE: ; Write the contents of 20H as Address and 21H contents as Data
	LCALL I2C_START
	MOV A,#0A0H ; A command for AT21C02A for writing
	LCALL I2C_WRITE
	MOV A,20H ; The address for the data to be written in side AT21C02A
	LCALL I2C_WRITE
	MOV A,21H ; The data
	LCALL I2C_WRITE
	LCALL I2C_STOP
	RET
	
I2C_READ:
	SETB SDA
	LCALL DELAY_10us
	MOV 50H,#08H
	AGAIN_I2C_READ:
		SETB SCL
		LCALL DELAY_10us
		RL A
		MOV C,SDA
		MOV ACC.0,C
		LCALL DELAY_10us
		CLR SCL
		LCALL DELAY_10us
		DJNZ 50H,AGAIN_I2C_READ
	RET

I2C_WRITE:
	MOV 50H,#08H
	AGAIN_I2C_WRITE:
		MOV C,ACC.7
		MOV SDA,C
		RL A
		LCALL DELAY_10us
		SETB SCL
		LCALL DELAY_10us
		CLR SCL
		LCALL DELAY_10us
		DJNZ 50H,AGAIN_I2C_WRITE
	SETB SDA
	LCALL DELAY_10us
	SETB SCL
	MOV 50H,#255
		WAIT_FOR_OK_WRITE:
			JNB SDA,OK_SIGNAL_WRITE
			DJNZ 50H,WAIT_FOR_OK_WRITE
		CLR B.0
		CLR SCL
		LCALL DELAY_10us
		RET
	OK_SIGNAL_WRITE:
		SETB B.0
		CLR SCL
		LCALL DELAY_10us
		RET

I2C_START:
	SETB SDA
	LCALL DELAY_10us
	SETB SCL
	LCALL DELAY_10us
	CLR SDA
	LCALL DELAY_10us
	CLR SCL
	LCALL DELAY_10us
	RET
	
I2C_STOP:
	CLR SDA
	LCALL DELAY_10us
	SETB SCL
	LCALL DELAY_10us
	SETB SDA
	LCALL DELAY_10us
	RET

CLEAR_LCD:
	CLR RS
	MOV LCD_DATA,#01H ; Clear display screen
	LCALL SEND_LCD_DATA
	MOV LCD_DATA,#0FH ; Display on, cursor blinking
	LCALL SEND_LCD_DATA
	MOV LCD_DATA,#38H ; 2 lines and 5 7 matrix Mode
	LCALL SEND_LCD_DATA
	MOV LCD_DATA,#80H ; Force cursor to the beginning ( 1st line)
	LCALL SEND_LCD_DATA
	SETB RS
	RET

SEND_LCD_DATA: ; Excute the Data ready on LCD_DATA pins
	SETB EN
	LCALL DELAY_5mS ; Wait 5mS for data processing in LCD 
	CLR EN
	RET

NUMBER_TO_ASCII: ; This converts the values in R2-R5 into Their's ASCII characters
	CJNE A,#10,CONTINUE
	CONTINUE:
		JC NUMBER
		ADD A,#37H
	SJMP FINISH_NUMBER_TO_ASCII
	NUMBER:
		ADD A,#30H
	FINISH_NUMBER_TO_ASCII:
	RET

DELAY_5mS:  ; R7 value will decide how many mS of Delay
	MOV TMOD,#01H
	CLR TF0
	CLR TR0
	MOV 51H,#05H
	AGAIN_DELAY_5mS:
		MOV TH0,#0FCH ; For 1mS
		MOV TL0,#67H  ; For 1mS
		SETB TR0
		TF0_WAIT:
			JNB TF0,TF0_WAIT
		CLR TF0
		CLR TR0
		DJNZ 51H,AGAIN_DELAY_5mS  ; R7 value will decide how many mS
	RET

DELAY_10us:
	NOP
	NOP
	NOP
	NOP
	NOP
	RET

DELAY_1s:
	PUSH 30H
	PUSH 31H
	PUSH 32H
	MOV 30H,#8
	MOV 31H,#1
	MOV 32H,#236
	AGAIN_DELAY_1s:
		DJNZ 32H,AGAIN_DELAY_1s
		DJNZ 31H,AGAIN_DELAY_1s
		DJNZ 30H,AGAIN_DELAY_1s
	POP 32H
	POP 31H
	POP 30H
	RET

DELAY_500ms:
	PUSH 30H
	PUSH 31H
	PUSH 32H
	MOV 30H,#4
	MOV 31H,#1
	MOV 32H,#236
	AGAIN_DELAY_500ms:
		DJNZ 32H,AGAIN_DELAY_500ms
		DJNZ 31H,AGAIN_DELAY_500ms
		DJNZ 30H,AGAIN_DELAY_500ms
	POP 32H
	POP 31H
	POP 30H
	RET

BUTTON_4X4:
	MOV P1, #0FFH
	CLR P1.7 ; Send signal to 1st Row
	NEXT1:	JB P1.3, NEXT2 ; Check 1st Column
		MOV A,#01H
		SJMP BUTTON_PRESSED
	NEXT2:  JB P1.2, NEXT3 ; Check 2nd Column
		MOV A,#02H
		SJMP BUTTON_PRESSED
	NEXT3:  JB P1.1, NEXTA ; Check 3rd Column
		MOV A,#03H
		SJMP BUTTON_PRESSED
	NEXTA:  JB P1.0, NEXT4 ; Check 4th Column
		MOV A,#0AH
		SJMP BUTTON_PRESSED
	NEXT4:  SETB P1.7
		CLR P1.6 ; Send signal to 2nd Row
		JB P1.3, NEXT5 ; Check 1st Column
		MOV A,#04H
		SJMP BUTTON_PRESSED
	NEXT5:  JB P1.2, NEXT6 ; Check 2nd Column
		MOV A,#05H
		SJMP BUTTON_PRESSED
	NEXT6:  JB P1.1, NEXTB ; Check 3rd Column
		MOV A,#06H
		SJMP BUTTON_PRESSED
	NEXTB:  JB P1.0, NEXT7 ; Check 4th Column
		MOV A,#0BH
		SJMP BUTTON_PRESSED
	NEXT7:  SETB P1.6
		CLR P1.5 ; Send signal to 3rd Row
		JB P1.3, NEXT8 ; Check 1st Column
		MOV A,#07H
		SJMP BUTTON_PRESSED
	NEXT8:  JB P1.2, NEXT9 ; Check 2nd Column
		MOV A,#08H
		SJMP BUTTON_PRESSED
	NEXT9:  JB P1.1, NEXTC ; Check 3rd Column
		MOV A,#09H
		SJMP BUTTON_PRESSED
	NEXTC:  JB P1.0, NEXTF ; Check 4th Column
		MOV A,#0CH
		SJMP BUTTON_PRESSED
	NEXTF:  SETB P1.5
		CLR P1.4 ; Send signal to 4th Row
		JB P1.3, NEXT0 ; Check 1st Column
		MOV A,#0FH
		SJMP BUTTON_PRESSED
	NEXT0:  JB P1.2, NEXTE ; Check 2nd Column
		MOV A,#00H
		SJMP BUTTON_PRESSED
	NEXTE:  JB P1.1, NEXTD ; Check 3rd Column
		MOV A,#0EH
		SJMP BUTTON_PRESSED
	NEXTD:  JB P1.0, NO_BUTTON ; Check 4th Column
		MOV A,#0DH
		SJMP BUTTON_PRESSED
	NO_BUTTON:  MOV A,#55H
		    LCALL DELAY_10us
		    MOV 47H,A
	 	    LCALL DELAY_10us
	BUTTON_PRESSED:
		CJNE A,#55H, OK_1
		LJMP BUTTON_4X4
	OK_1:   CJNE A,47H, OK_2
		LJMP BUTTON_4X4
	OK_2:
		LCALL DELAY_10us
		MOV 47H,A
		LCALL DELAY_10us
	RET

INTRO:
	LCALL CLEAR_LCD
	MOV DPTR,#TEXT_INTRO
	AGAIN_INTRO:
		CLR A
		MOVC A,@A+DPTR
		JZ FINISH_INTRO
		MOV LCD_DATA,A
		LCALL SEND_LCD_DATA
		INC DPTR
		SJMP AGAIN_INTRO
	FINISH_INTRO:
	RET
	
DONE:
	LCALL CLEAR_LCD
	MOV DPTR,#TEXT_DONE
	AGAIN_DONE:
		CLR A
		MOVC A,@A+DPTR
		JZ FINISH_DONE
		MOV LCD_DATA,A
		LCALL SEND_LCD_DATA
		INC DPTR
		SJMP AGAIN_DONE
	FINISH_DONE:
	RET
	
CHOICE_R_OR_W:
	LCALL LCD_SECOND_LINE
	MOV DPTR,#TEXT_CHOICE_R_OR_W
	AGAIN_CHOICE_R_OR_W:
		CLR A
		MOVC A,@A+DPTR
		JZ FINISH_CHOICE_R_OR_W
		MOV LCD_DATA,A
		LCALL SEND_LCD_DATA
		INC DPTR
		SJMP AGAIN_CHOICE_R_OR_W
	FINISH_CHOICE_R_OR_W:
	CLR RS
	MOV LCD_DATA,#0C7H ; Force LCD cursor to the 2nd line 7th character
	LCALL SEND_LCD_DATA
	SETB RS
	RET

WRITE_INFORMATION:
	LCALL CLEAR_LCD
	MOV DPTR,#TEXT_WRITE_INFORMATION
	AGAIN_WRITE_INFORMATION:
		CLR A
		MOVC A,@A+DPTR
		JZ FINISH_WRITE_INFORMATION
		MOV LCD_DATA,A
		LCALL SEND_LCD_DATA
		INC DPTR
		SJMP AGAIN_WRITE_INFORMATION
	FINISH_WRITE_INFORMATION:
	CLR RS
	MOV LCD_DATA,#0C3H ; Force LCD cursor to the 2nd line 3rd character
	LCALL SEND_LCD_DATA
	SETB RS
	RET
	
READ_INFORMATION:
	LCALL CLEAR_LCD
	MOV DPTR,#TEXT_READ_INFORMATION
	AGAIN_READ_INFORMATION:
		CLR A
		MOVC A,@A+DPTR
		JZ FINISH_READ_INFORMATION
		MOV LCD_DATA,A
		LCALL SEND_LCD_DATA
		INC DPTR
		SJMP AGAIN_READ_INFORMATION
	FINISH_READ_INFORMATION:
	CLR RS
	MOV LCD_DATA,#0C3H ; Force LCD cursor to the 2nd line 3rd character
	LCALL SEND_LCD_DATA
	SETB RS
	RET
	
LCD_SECOND_LINE_C:
	CLR RS
	MOV LCD_DATA,#0CCH ; Force LCD cursor to the 2nd line 13th character
	LCALL SEND_LCD_DATA
	SETB RS
	RET
	
LCD_SECOND_LINE:
	CLR RS
	MOV LCD_DATA,#0C0H ; Force cursor to the beginning ( 2nd line)
	LCALL SEND_LCD_DATA
	SETB RS
	RET
	
TEXT_INTRO:             DB '   EEPROM  R/W  ',00H
TEXT_CHOICE_R_OR_W:     DB 'CHOICE? 1:R  2:W',00H
TEXT_WRITE_INFORMATION: DB 'ADDRESS?   DATA?',00H
TEXT_DONE:              DB '       DONE!    ',00H
TEXT_READ_INFORMATION:  DB 'ADDRESS?   DATA=',00H
END
