; ==============================================================================
; EE 390 - Practical Assignment 1: Bird Sound Synthesizer       STARTER TEMPLATE
; Board : Puzhong 51 A2 (STC89C52RC, 11.0592 MHz, 12T mode)
;
; Name(s)  :
; Group    :
; Date     :
;
; This template gives you the pin names and the vector layout. Nothing else here
; is required: the program structure, the routine names and the table format are
; your design. Add, rename or delete whatever you like.
;
; Stage 1 (checkpoint) : each button plays its own tone, from a delay loop.
;                        See S1-S6 on the project page.
; Stage 2 (final)      : one bird call of your choice, played from a table, with
;                        the pitch generated by polling Timer 0. See R1-R9.
; ==============================================================================

; ---------------------------------------------------------------- pins --------
BUZZER   EQU P2.5   ; passive buzzer (PNP driver: LOW = on)
LED1     EQU P2.0   ; LEDs D1..D4 (active LOW)
LED2     EQU P2.1
LED3     EQU P2.2
LED4     EQU P2.3
K1       EQU P3.1   ; push buttons (read 0 when pressed)
K2       EQU P3.0
K3       EQU P3.2
K4       EQU P3.3

; ---------------------------------------------------------------- RAM ---------
; TODO: addresses for your table pointer, note index, tick counter, etc.

; ---------------------------------------------------------------- vectors -----
ORG 0000H
	LJMP MAIN

ORG 0030H
; ------------------------------------------------------------------------------
; MAIN
; ------------------------------------------------------------------------------
MAIN:
	; TODO: set up the stack, ports and (stage 2) timers

LOOP:
	; Stage 1 - TODO: while a button is held, sound its tone and light its LED
	; Stage 2 - TODO: on a new press, play your call once, LED on while it plays.
	;           Poll TF0 for pitch and TF1 for note timing; reload and clear
	;           each flag yourself when it's set. No interrupts.
	SJMP LOOP

; ------------------------------------------------------------------------------
; STAGE 1: tone from a delay loop
; ------------------------------------------------------------------------------
TONE:
	; TODO: toggle BUZZER at the pitch you want, for as long as you want it
	RET

; ------------------------------------------------------------------------------
; STAGE 2: playing a call from a table, with pitch and timing from polled timers
; ------------------------------------------------------------------------------
PLAY_CALL:
	; TODO
	RET

; ==============================================================================
; SOUND TABLE (stage 2)
;
; Document your own format here: how a note, a rest and the end of the call are
; encoded. One routine should be able to play anything written in this format.
; ==============================================================================
; Format:
;

CALL_TABLE:         ; the bird you chose
	; TODO

END
